# Generated by Django 5.2.9 on 2025-12-06 05:01

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Node',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('node_name', models.CharField(help_text="Human-readable name for this node (e.g., 'Node A', 'Hilltop Node')", max_length=100)),
                ('esp32_device_id', models.CharField(help_text='Unique hardware identifier for the ESP32 device', max_length=100, unique=True)),
                ('lora_node_id', models.CharField(help_text='LoRa network address or node ID', max_length=50)),
                ('status', models.CharField(choices=[('ONLINE', 'Online'), ('OFFLINE', 'Offline')], default='OFFLINE', help_text='Current connection status', max_length=10)),
                ('last_seen', models.DateTimeField(blank=True, help_text='Last time this node updated its status', null=True)),
                ('description', models.TextField(blank=True, help_text='Optional description or location information')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(help_text='The Django user account linked to this node', on_delete=django.db.models.deletion.CASCADE, related_name='node_profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['node_name'],
            },
        ),
    ]
