# Generated by Django 5.2.9 on 2025-12-06 07:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='node',
            name='contact_email',
            field=models.EmailField(blank=True, help_text='Contact email for this node/operator', max_length=254),
        ),
        migrations.AddField(
            model_name='node',
            name='contact_name',
            field=models.CharField(blank=True, help_text='Name of the person responsible for this node', max_length=100),
        ),
        migrations.AddField(
            model_name='node',
            name='contact_phone',
            field=models.CharField(blank=True, help_text='Contact phone number', max_length=20),
        ),
    ]
