# Generated by Django 5.2.9 on 2025-12-06 05:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField(help_text='The message content/payload')),
                ('message_type', models.CharField(choices=[('TEXT', 'Text')], default='TEXT', help_text='Type of message', max_length=10)),
                ('status', models.CharField(choices=[('SENT', 'Sent'), ('DELIVERED', 'Delivered')], default='SENT', help_text='Delivery status', max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('receiver', models.ForeignKey(help_text='The node that should receive this message', on_delete=django.db.models.deletion.CASCADE, related_name='received_messages', to='accounts.node')),
                ('sender', models.ForeignKey(help_text='The node that sent this message', on_delete=django.db.models.deletion.CASCADE, related_name='sent_messages', to='accounts.node')),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['-created_at'], name='communicati_created_d9a4d7_idx'), models.Index(fields=['receiver', '-created_at'], name='communicati_receive_b100d8_idx')],
            },
        ),
    ]
